### ISSUE TITLE
Leaving Connection Open w/o data Produces Exceptions. 

### ISSUE THREAD

**Issue by JettScythe** [JettScythe/MemoBirb#2]
`Traceback (most recent call last):
  File "/home/jettscythe/Documents/pybitdb/memo/lib/python3.7/site-packages/urllib3/response.py", line 601, in _update_chunk_length
    self.chunk_left = int(line, 16)
ValueError: invalid literal for int() with base 16: b''

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/jettscythe/Documents/pybitdb/memo/lib/python3.7/site-packages/urllib3/response.py", line 360, in _error_catcher
    yield
  File "/home/jettscythe/Documents/pybitdb/memo/lib/python3.7/site-packages/urllib3/response.py", line 666, in read_chunked
    self._update_chunk_length()
  File "/home/jettscythe/Documents/pybitdb/memo/lib/python3.7/site-packages/urllib3/response.py", line 605, in _update_chunk_length
    raise httplib.IncompleteRead(line)
http.client.IncompleteRead: IncompleteRead(0 bytes read)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/jettscythe/Documents/pybitdb/memo/lib/python3.7/site-packages/requests/models.py", line 750, in generate
    for chunk in self.raw.stream(chunk_size, decode_content=True):
  File "/home/jettscythe/Documents/pybitdb/memo/lib/python3.7/site-packages/urllib3/response.py", line 490, in stream
    for line in self.read_chunked(amt, decode_content=decode_content):
  File "/home/jettscythe/Documents/pybitdb/memo/lib/python3.7/site-packages/urllib3/response.py", line 694, in read_chunked
    self._original_response.close()
  File "/usr/lib/python3.7/contextlib.py", line 130, in __exit__
    self.gen.throw(type, value, traceback)
  File "/home/jettscythe/Documents/pybitdb/memo/lib/python3.7/site-packages/urllib3/response.py", line 378, in _error_catcher
    raise ProtocolError('Connection broken: %r' % e, e)
urllib3.exceptions.ProtocolError: ('Connection broken: IncompleteRead(0 bytes read)', IncompleteRead(0 bytes read))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "bitsocketscraper.py", line 51, in <module>
    }, bitsocket_handler)
  File "bitsocketscraper.py", line 26, in query_bitsocket
    for evt in client.events():
  File "/home/jettscythe/Documents/pybitdb/memo/lib/python3.7/site-packages/sseclient/__init__.py", line 58, in events
    for chunk in self._read():
  File "/home/jettscythe/Documents/pybitdb/memo/lib/python3.7/site-packages/sseclient/__init__.py", line 48, in _read
    for chunk in self._event_source:
  File "/home/jettscythe/Documents/pybitdb/memo/lib/python3.7/site-packages/requests/models.py", line 753, in generate
    raise ChunkedEncodingError(e)
requests.exceptions.ChunkedEncodingError: ('Connection broken: IncompleteRead(0 bytes read)', IncompleteRead(0 bytes read))
`
Not sure if it's cascading or what. Gonna try and get more than a catch-all-exceptions-fix today.

**Comment by JettScythe** [comment]
Temp fix is in place as the catch-all. 
Not ideal but works for now.

**Comment by JettScythe** [comment]
Except:
  pass
didn't actually work at all from what I can tell. Any help would be appreciated.
